/** Textos de ajuda — formulário AMAP Multi-Trade (tooltips e descrições visíveis). */

export const MT_HELP = {
  rule1: {
    group: 'Compra quando o RSI indica oversold e vende por RSI ou stop. Opera em posição separada da regra 2 — as duas podem estar abertas ao mesmo tempo no mesmo par.',
    enabled: 'Liga o caminho RSI: o bot monitora o RSI de entrada e abre posição própria (estado R1 no bot). Desligado = só a regra 2 pode entrar, se estiver ativa.',
    entryRsi: 'Gatilho principal da regra 1. Ex.: RSI(15m) < 30 = candle fechou com RSI abaixo de 30. Só dispara entrada se filtros MA, extensão e volume permitirem.',
    maFilters: 'Exigem que o preço esteja acima de uma ou mais médias antes de comprar no RSI. Evita comprar oversold em queda livre longe da tendência. Desligado = entrada só pelo RSI.',
    maPeriod: 'Período da média móvel exponencial (EMA). EMA50 é o padrão clássico; EMA200 exige tendência mais longa.',
    maInterval: 'Timeframe em que a MA é calculada. MA em 4h filtra macro; em 1h reage mais rápido.',
    maModeStrict: 'Preço deve fechar acima da MA. Bloqueia entrada se o close estiver abaixo — típico para confirmar tendência de alta.',
    maModeAdaptive: 'Permite dip abaixo da MA até um % histórico (pullback). Calcula dips passados que recuperaram e usa esse piso em vez de exigir close estritamente acima.',
    maAboveCandles: 'Antes do sinal RSI, exige N candles fechados consecutivos com close acima da MA. Confirma que o ativo já estava em tendência antes do oversold.',
    maDipFixed: 'Opcional: força um dip máximo fixo (%) abaixo da MA no modo adaptativo, em vez de usar só o histórico. Use Sugerir para ver o valor típico da moeda.',
    extension: 'Bloqueia compra quando o preço está esticado demais acima da MA de referência — evita entrar no topo após sequência de altas.',
    extensionRef: 'MA usada para medir se o preço está “esticado” (% acima). Normalmente MA50 no mesmo timeframe dos candles de confirmação.',
    extension3: 'Bloqueia se os últimos 3 candles fechados forem de alta (close > open) no intervalo escolhido — sinal de exaustão / compra tardia.',
    extension4: 'Bloqueia se houver 3 altas seguidas + 1 candle de queda no intervalo — padrão de topo com primeira correção.',
    extensionLogic: '“Basta uma” = 3 OU 4 candles já bloqueiam. “Exige ambas” = só bloqueia se as duas condições forem verdadeiras (mais restritivo).',
    execImmediate: 'Mercado na hora do sinal: compra assim que RSI + filtros passam. Desligado = ordem limite PENDING abaixo do preço do gatilho.',
    execDiscount: 'Com PENDING: alvo de compra fica X% abaixo do close no momento do sinal RSI. Busca preço melhor; pode não executar se o mercado subir direto.',
    execTimeout: 'Tempo máximo em PENDING. Após isso cancela a entrada se o preço não atingiu o desconto.',
    execCancelPct: 'Cancela PENDING se o preço subir X% acima do gatilho sem ter comprado — evita perseguir movimento que já escapou.',
    execCancelExitRsi: 'Cancela PENDING se o RSI de saída for atingido antes da compra. Evita comprar depois que o ativo já se recuperou (entrada tardia).',
    exitRsi: 'Vende a posição da regra 1 quando o RSI de saída é atingido (ex.: RSI(1h) > 70). Independente da regra 2.',
    stopOverview: 'Proteção da regra 1 apenas. Se MA fixa e adaptativa estiverem ativas, vende no stop mais alto (menos agressivo) que for violado na queda.',
    stopFixed: 'Vende se o close ficar abaixo da MA fixa no timeframe escolhido — stop clássico por perda de suporte.',
    stopFixedAbove: 'Só arma o stop fixo depois de N candles fechados acima da MA — evita stop prematuro logo após a entrada.',
    stopAdaptive: 'Piso = MA × (1 − dip% histórico da moeda). Acompanha pullbacks normais sem usar a mesma MA dos filtros de entrada.',
    stopAdaptiveAbove: 'Exige N candles acima da MA do piso antes de considerar o stop adaptativo — mesma lógica do stop fixo.',
    stopPctCap: 'Quando MA fixa e adaptativa estão desligadas: vende se a perda ultrapassar X% do preço de compra. Última rede de segurança.',
  },

  rule2: {
    group: 'Compra no pullback à MA após N candles em tendência (close acima da MA). Saída por RSI e stop na própria MA. Posição independente da regra 1.',
    enabled: 'Liga entrada por MA (toque ou cruzamento). Não reentra se já houver posição R2 em PENDING ou BOUGHT no par.',
    entryMa: 'Define qual MA observar e como detectar o pullback após a sequência de candles acima.',
    triggerTouch: 'Entra quando o preço toca a MA dentro da tolerância (%) — compra no suporte, sem exigir cruzamento.',
    triggerCross: 'Entra quando o candle cruza a MA de baixo para cima — confirma retomada da tendência após o dip.',
    aboveMa: 'Exige N candles anteriores ao sinal com close acima da MA. Garante que houve tendência antes do pullback, não compra em ativo lateral.',
    tolerance: 'Distância máxima (%) para considerar “toque” na MA. Muito baixo = menos sinais; alto = entradas mais folgadas.',
    execPending: 'Regra 2 sempre usa PENDING (nunca mercado imediato): ordem limite abaixo do gatilho MA para pegar o dip no suporte.',
    execDiscount: 'Alvo de compra X% abaixo do preço do gatilho MA — similar à regra 1, ajustado ao pullback.',
    exitRsiLogic: 'Com várias condições RSI: “qualquer” vende se uma bater; “todas” exige que todas estejam ativas (saída mais tardia).',
    exitRsiCond: 'Cada linha é um RSI independente (ex.: 1h > 70 OU 15m > 80). Útil para garantir saída em timeframe rápido ou lento.',
    stopAdaptive: 'Stop na mesma MA da entrada × (1 − dip% histórico). Protege se o pullback virar reversão, sem stop fixo arbitrário.',
    stopAboveMa: 'Só considera o stop depois de N candles fechados acima da MA de entrada — evita sair no primeiro ruído abaixo da média.',
  },

  shared: {
    symbol: 'Par USDT negociado na exchange escolhida (ex.: BTCUSDT).',
    exchange: 'Binance ou Gate.io — candles, volume e ordens usam esta corretora.',
    strategy15m: 'Preset AMAP com RSI de entrada em 15m — mais sinais, operações mais curtas. Capital e config separados da estratégia 1h.',
    strategy1h: 'Preset AMAP com RSI de entrada em 1h — menos ruído, swings maiores. Pode rodar em paralelo com 15m no mesmo símbolo.',
    strategyEnable: 'Liga ou desliga esta estratégia no bot. Desligada com registro salvo = bot ignora este timeframe.',
    capital: 'USDT alocados só para esta estratégia. Regra 1 e 2 dentro da mesma estratégia compartilham esse capital (uma posição por regra).',
    volume: 'Volume 24h mínimo em USDT. Abaixo do mínimo o painel avisa; na saída o bot pode usar mercado para garantir liquidez.',
    pollNormal: 'Intervalo entre checagens quando o RSI de saída está longe do alvo.',
    pollFast: 'Intervalo mais curto quando o RSI de saída se aproxima do valor configurado — não perde o pico de venda.',
    pollFastThreshold: 'RSI de saída ≥ este valor ativa o polling rápido.',
    adaptiveOpts: 'Parâmetros do cálculo de dip histórico (padrão, teto, piso e mínimo de episódios) usados nos filtros MA adaptativos e stops.',
  },
};
