
// model/currency-model.js
const CurrencyModel = {
  currencies: [],
  filters: [
    {
      name: '1h|Binance|USDT',
      // Lista atualizada em 30/08/2024
      list: [
        "RESOLVUSDT",
        "ALCXUSDT",
        "MANTAUSDT",
        "SANTOSUSDT",
        "QNTUSDT",
        "SYRUPUSDT",
        "GLMUSDT",
        "XLMUSDT",
        "NFPUSDT",
        "MLNUSDT",
        "METISUSDT",
        "WLFIUSDT",
        "FFUSDT",
        "ACXUSDT",
        "XRPUSDT",
        "TURTLEUSDT",
        "FLOKIUSDT",
        "WIFUSDT",
        "LAZIOUSDT",
        "LAUSDT",
        "INITUSDT",
        "GTCUSDT",
        "MOVRUSDT",
        "MORPHOUSDT",
        "TIAUSDT",
        "SOPHUSDT",
        "NXPCUSDT",
        "DOGEUSDT",
        "PORTOUSDT",
        "LINKUSDT",
        "ADAUSDT",
        "ALPINEUSDT",
        "GASUSDT",
        "GUNUSDT",
        "NOTUSDT",
        "TONUSDT",
        "COMPUSDT",
        "OPUSDT",
        "AAVEUSDT",
        "EIGENUSDT",
        "DASHUSDT",
        "ALGOUSDT",
        "LDOUSDT",
        "LQTYUSDT",
        "TURBOUSDT",
        "IMXUSDT",
        "RSRUSDT",
        "SHIBUSDT",
        "WBETHUSDT",
        "SUSDT",
        "ERAUSDT",
        "CRVUSDT",
        "QIUSDT",
        "ETHUSDT",
        "BNTUSDT",
        "1000SATSUSDT",
        "TRBUSDT",
        "INJUSDT",
        "PEPEUSDT",
        "JTOUSDT",
        "FLOWUSDT",
        "IOTAUSDT",
        "CHZUSDT",
        "GNOUSDT",
        "POLUSDT",
        "VIRTUALUSDT",
        "IOTXUSDT",
        "ETHFIUSDT",
        "AMPUSDT",
        "ZROUSDT",
        "KAIAUSDT",
        "ENAUSDT",
        "OGNUSDT",
        "GHSTUSDT",
        "LUNCUSDT",
        "FXSUSDT",
        "A2ZUSDT",
        "LINEAUSDT",
        "HFTUSDT",
        "SUIUSDT",
        "MEUSDT",
        "EDUUSDT",
        "XTZUSDT",
        "HUMAUSDT",
        "APTUSDT",
        "BNSOLUSDT",
        "GIGGLEUSDT",
        "ETCUSDT",
        "DATAUSDT",
        "STGUSDT",
        "JUVUSDT",
        "ALTUSDT",
        "1INCHUSDT",
        "ONDOUSDT",
        "MITOUSDT",
        "GALAUSDT",
        "SOLUSDT",
        "NTRNUSDT",
        "YFIUSDT",
        "GNSUSDT",
        "PYTHUSDT",
        "PONDUSDT",
        "FIDAUSDT",
        "LAYERUSDT",
        "AGLDUSDT",
        "ENSUSDT",
        "ORDIUSDT",
        "RIFUSDT",
        "DYDXUSDT",
        "WLDUSDT",
        "EGLDUSDT",
        "QUICKUSDT",
        "APEUSDT",
        "EDENUSDT",
        "BCHUSDT",
        "ARBUSDT",
        "DUSDT",
        "CTSIUSDT",
        "RONINUSDT",
        "USUALUSDT",
        "TRXUSDT",
        "GMXUSDT",
        "DENTUSDT",
        "ZILUSDT",
        "ACAUSDT",
        "BONKUSDT",
        "RENDERUSDT",
        "UTKUSDT",
        "CKBUSDT",
        "AXSUSDT",
        "SNXUSDT",
        "USTCUSDT",
        "WUSDT",
        "PENGUUSDT",
        "HBARUSDT",
        "PAXGUSDT",
        "SANDUSDT",
        "BEAMXUSDT",
        "LRCUSDT",
        "BARUSDT",
        "1MBABYDOGEUSDT",
        "RAYUSDT",
        "RUNEUSDT",
        "SKLUSDT",
        "HOLOUSDT",
        "FIOUSDT",
        "AVAXUSDT",
        "COTIUSDT",
        "XECUSDT",
        "BLURUSDT",
        "JASMYUSDT",
        "NILUSDT",
        "PLUMEUSDT",
        "BIFIUSDT",
        "ARKMUSDT",
        "SEIUSDT",
        "XVSUSDT",
        "GLMRUSDT",
        "BERAUSDT",
        "MTLUSDT",
        "PENDLEUSDT",
        "VICUSDT",
        "MAVUSDT",
        "TSTUSDT",
        "BTCUSDT",
        "BICOUSDT",
        "HYPERUSDT",
        "STXUSDT",
        "PSGUSDT",
        "DFUSDT",
        "WBTCUSDT",
        "KMNOUSDT",
        "PNUTUSDT",
        "AUDIOUSDT",
        "ATAUSDT",
        "DOTUSDT",
        "MANAUSDT",
        "CITYUSDT",
        "SAGAUSDT",
        "FUNUSDT",
        "MBLUSDT",
        "NEOUSDT",
        "XVGUSDT",
        "BNBUSDT",
        "TUSDT",
        "DODOUSDT",
        "SLPUSDT",
        "IDUSDT",
        "NEARUSDT",
        "WANUSDT",
        "ACEUSDT",
        "EPICUSDT",
        "QTUMUSDT",
        "MOVEUSDT",
        "STRAXUSDT",
        "CVXUSDT",
        "0GUSDT",
        "FORTHUSDT",
        "NEIROUSDT",
        "PROVEUSDT",
        "ROSEUSDT",
        "LUMIAUSDT",
        "SUNUSDT",
        "MAGICUSDT",
        "WOOUSDT",
        "GMTUSDT",
        "HIVEUSDT",
        "VETUSDT",
        "JUPUSDT",
        "KNCUSDT",
        "CTKUSDT",
        "REQUSDT",
        "BIGTIMEUSDT",
        "ASTERUSDT",
        "2ZUSDT",
        "CETUSUSDT",
        "DOLOUSDT",
        "XPLUSDT",
        "KAVAUSDT",
        "ATOMUSDT",
        "POWRUSDT",
        "XAIUSDT",
        "THEUSDT",
        "BROCCOLI714USDT",
        "BANDUSDT",
        "CGPTUSDT",
        "DOGSUSDT",
        "DEXEUSDT",
        "MDTUSDT",
        "RDNTUSDT",
        "PEOPLEUSDT",
        "AEVOUSDT",
        "BOMEUSDT",
        "TLMUSDT",
        "CAKEUSDT",
        "LPTUSDT",
        "BANANAUSDT",
        "GPSUSDT",
        "DIAUSDT",
        "RPLUSDT",
        "SYNUSDT",
        "PARTIUSDT",
        "AVAUSDT",
        "ASTRUSDT",
        "PHBUSDT",
        "ACHUSDT",
        "REZUSDT",
        "REDUSDT",
        "MBOXUSDT",
        "EURIUSDT",
        "WALUSDT",
        "EURUSDT",
        "THETAUSDT",
        "TUTUSDT",
        "OPENUSDT",
        "ONEUSDT",
        "SXPUSDT",
        "TKOUSDT",
        "WINUSDT",
        "TFUELUSDT",
        "ANIMEUSDT",
        "SIGNUSDT",
        "TWTUSDT",
        "LTCUSDT",
        "STOUSDT",
        "SCUSDT",
        "QKCUSDT",
        "MIRAUSDT",
        "CHESSUSDT",
        "FTTUSDT",
        "USDCUSDT",
        "BELUSDT",
        "C98USDT",
        "DEGOUSDT",
        "ICXUSDT",
        "LSKUSDT",
        "OXTUSDT",
        "TRUUSDT",
        "NKNUSDT",
        "VOXELUSDT",
        "BTTCUSDT",
        "NEXOUSDT",
        "CYBERUSDT",
        "VANRYUSDT",
        "PORTALUSDT",
        "IOUSDT",
        "HMSTRUSDT",
        "SCRUSDT",
        "TRUMPUSDT",
        "BMTUSDT",
        "USD1USDT",
        "AUSDT",
        "NEWTUSDT",
        "BFUSDUSDT",
        "USDPUSDT",
        "FDUSDUSDT",
        "XUSDUSDT",
        "USDEUSDT",
        "TUSDUSDT",
        "AEURUSDT",
        "SAHARAUSDT",
        "AXLUSDT",
        "YBUSDT",
        "KAITOUSDT",
        "ANKRUSDT",
        "UMAUSDT",
        "COSUSDT",
        "LUNAUSDT",
        "PUNDIXUSDT",
        "AVNTUSDT",
        "OGUSDT",
        "AUCTIONUSDT",
        "ENJUSDT",
        "GRTUSDT",
        "GUSDT",
        "HOOKUSDT",
        "RVNUSDT",
        "REIUSDT",
        "BABYUSDT",
        "SXTUSDT",
        "MASKUSDT",
        "KSMUSDT",
        "CELRUSDT",
        "MINAUSDT",
        "NMRUSDT",
        "NOMUSDT",
        "OSMOUSDT",
        "ORCAUSDT",
        "ATMUSDT",
        "CELOUSDT",
        "DYMUSDT",
        "AIXBTUSDT",
        "UNIUSDT",
        "HIGHUSDT",
        "CVCUSDT",
        "ONGUSDT",
        "SSVUSDT",
        "FLUXUSDT",
        "ARPAUSDT",
        "WAXPUSDT",
        "MUBARAKUSDT",
        "ZKUSDT",
        "HOTUSDT",
        "ACTUSDT",
        "ACMUSDT",
        "LISTAUSDT",
        "BANANAS31USDT",
        "STEEMUSDT",
        "TOWNSUSDT",
        "SKYUSDT",
        "ILVUSDT",
        "AIUSDT",
        "BIOUSDT",
        "BATUSDT",
        "ARKUSDT",
        "EULUSDT",
        "TREEUSDT",
        "ARDRUSDT",
        "IDEXUSDT",
        "API3USDT",
        "STRKUSDT",
        "ASRUSDT",
        "TNSRUSDT",
        "WCTUSDT",
        "RLCUSDT",
        "TAOUSDT",
        "SHELLUSDT",
        "RAREUSDT",
        "ALICEUSDT",
        "1000CATUSDT",
        "FISUSDT",
        "YGGUSDT",
        "MEMEUSDT",
        "PIXELUSDT",
        "BBUSDT",
        "ZRXUSDT",
        "VTHOUSDT",
        "SYSUSDT",
        "SOMIUSDT",
        "COOKIEUSDT",
        "ZKCUSDT",
        "CHRUSDT",
        "CFXUSDT",
        "FARMUSDT",
        "ONTUSDT",
        "SOLVUSDT",
        "VANAUSDT",
        "SUSHIUSDT",
        "OMUSDT",
        "SCRTUSDT",
        "HEMIUSDT",
        "1000CHEEMSUSDT",
        "POLYXUSDT",
        "ZBTUSDT",
        "MMTUSDT",
        "FILUSDT",
        "IOSTUSDT",
        "PUMPUSDT",
        "FETUSDT",
        "ZECUSDT",
        "COWUSDT",
        "SFPUSDT",
        "BARDUSDT",
        "ADXUSDT",
        "SPELLUSDT",
        "IQUSDT",
        "HAEDALUSDT",
        "DGBUSDT",
        "STORJUSDT",
        "JSTUSDT",
        "ARUSDT",
        "HOMEUSDT",
        "HEIUSDT",
        "PYRUSDT",
        "ICPUSDT",
        "JOEUSDT",
        "DUSKUSDT",
        "PROMUSDT",
        "CATIUSDT",
        "SUPERUSDT",
        "PHAUSDT",
        "XNOUSDT",
        "FORMUSDT",
        "ZENUSDT",
        "PIVXUSDT",
        "VELODROMEUSDT",
        "SAPIENUSDT",
        "RADUSDT",
        "KERNELUSDT",
        "FUSDT",
        "SPKUSDT",
        "KITEUSDT",
        "DCRUSDT",
        "AWEUSDT",
        "CUSDT",
        "ENSOUSDT",
        "ALLOUSDT"
      ]
    },
  ],
  quotes: ['USDT', 'BTC', 'BNB'],

  addCurrency: function (item) {
    let index = this.currencies.list.findIndex(obj => obj.symbol === item.symbol);

    // Se o objeto for econtrado, edite.
    if (index !== -1) {
      this.currencies[index] = item;
    }
  },
  getAllCurrencies: async function () {
    return await this.currencies;
  },
  getBinanceCurrenciesWithUsdt: async function (currencies) {

    let bincanceCurrenciesWithUsdt = this.filters[0].list;

    // Moedas estáveis que não quero capturar
    let stableCurrencies = ["TUSDUSDT", "USDPUSDT", "FDUSDUSDT", "EURIUSDT", "XUSDUSDT", "USDCUSDT", "EURUSDT", "USDEUSDT", "USD1USDT", "BFUSDUSDT"];


    let filteredCurrenciesByBinanceWithUsdt = currencies.list.filter(currency => bincanceCurrenciesWithUsdt.includes(currency.symbol) && !stableCurrencies.includes(currency.symbol));

    return filteredCurrenciesByBinanceWithUsdt;

  },
  addFilter: async function (item) {

    let index = this.filters.findIndex(obj => obj.name === item.name);

    // Se o objeto for econtrado, edite.
    if (index !== -1) {
      this.filters[index] = item;
    } else {
      this.filters.push(item)
    }


  },
  getQuotes: function () {
    return this.quotes;
  },
  getFilters: function () {
    return this.filters;
  },
  findFilter: function (name) {
    let filter = this.filters.find(filter => filter.name === name)

    return filter;
  },
  findCurrency: function () {
    this.currencies.list.find(currency.symbol)
  },
  joinFilters: function (selectedFilters) {

    let name = selectedFilters.join('|')

    let data = this.filters.filter(f => selectedFilters.includes(f.name))

    function getCommonSymbols(arrays) {
      if (arrays.length === 0) return [];

      // Start with the first list
      let commonSymbols = arrays[0].list;

      // Iterate through the remaining lists
      for (let i = 1; i < arrays.length; i++) {
        commonSymbols = commonSymbols.filter(symbol => arrays[i].list.includes(symbol));
      }

      return commonSymbols;
    }

    const commonSymbols = getCommonSymbols(data);

    this.addFilter({
      name: name,
      list: commonSymbols
    })

  },
  clearAllFilters: function () {
    this.filters = this.filters.filter(f => f.name === '1h|Binance|USDT')
  },
  removeFilters: function (filtersToRemove) {
    // Não pode remover o primeiro filtro
    let firstFilter = this.filters[0]
    let newFilters = this.filters.filter(f => !filtersToRemove.includes(f.name));
    this.filters = []
    this.filters.push(firstFilter);
    // Retira repetições
    let setFilters = new Set([firstFilter, ...newFilters])
    this.filters = Array.from(setFilters)

  },

  getForTestIndicatorsAndCurrencies: async function () {

    try {
      let response = await fetch('./indicators-and-currencies.json');  // Fetch the JSON file
      if (!response.ok) {
        throw new Error('Network response was not ok');
      }
      let data = await response.json();
      return data;  // Return the JSON data
    } catch (error) {
      console.error('There has been a problem with your fetch operation:', error);
      return null;  // Return null or handle the error as needed
    }
  }

};

export default CurrencyModel;